### ISSUE TITLE
Gulpfile is missing

### ISSUE THREAD

**Issue by dlangerenken** [bpmsoasolutions/es6-oraclejet#1]
Could you upload the gulpfile for this project? I assume it's similar to the oracle-jet-todo-app gulpfile ;)

**Comment by danibram** [comment]
Hey, yes its the same, but since we released our cli tool we dont use gulpfile, you can copy from the oracle-todo-app project, else you can use our cli tool, you have in the package json the commands you need to run. Also you can go to the previous commits and use it.
[ Link to cli tool](https://github.com/bpmsoasolutions/jet-builder-cli)
Thanks
